//! Long forms of diagnostic codes, for `lacon explain`.

const ENTRIES: &[(&str, &str)] = &[
    ("E0101", "Lexical error: a character or literal the lexer cannot read (stray character, unterminated string, bad escape, bad indentation). Indent with spaces; a dedent must return to an earlier indentation level."),
    ("E0110", "Syntax error: the parser expected one thing and found another. Blocks follow `:` (or `=` for functions) and are either the rest of the line or an indented block on the next lines."),
    ("E0120", "There is no `let`/`const`. `x = 1` binds an immutable name; `var x = 0` binds a mutable one. Rebinding an immutable name in the same block is allowed (`line = line.trim()`)."),
    ("E0121", "Functions are declared `fn name(param Type, ...) Ret =` followed by the body. The return type is omitted when nothing is returned; `T!` marks a function that can fail."),
    ("E0122", "Struct types are declared `type Name {field Type, ...}`; sum types are `enum Name = A(T) | B`. There are no classes."),
    ("E0123", "Blocks use `:` and indentation, not braces:\n  if x > 0:\n    print(x)\n  else: print(0)"),
    ("E0124", "`//` is not an operator. Comments start with `#`. Integer `/` already truncates."),
    ("E0125", "There are no `::` paths. Use `.`: `Shape.Circle(1.0)`, or just `Circle(1.0)` when the variant name is unique."),
    ("E0126", "There is no `:=`. Write `x = 1`, or `var x = 0` for a mutable binding."),
    ("E0127", "There is no `++`/`--`. Write `x += 1` on a `var`."),
    ("E0128", "There are no exceptions. A function that can fail returns `T!` and fails with `fail \"msg\"`. `f()?` passes an error up; `f() ?? default` replaces it; `match r` with an `err(e):` arm handles it."),
    ("E0129", "Lambdas are `|a, b| expr`. A lambda of one argument is usually written with `it`: `xs.map(it * 2)`, `xs.filter(it.age > 18)`. Lambda bodies are one expression, without braces."),
    ("E0130", "There are no macros. Print with `print(\"{x} and {y}\")`; every string interpolates."),
    ("E0131", "Generic parameters use brackets: `fn max[T](a T, b T) T`. Standard types have short forms: `[T]` list, `{K:V}` map, `{T}` set, `T?` optional, `T!` result."),
    ("E0132", "There are no references or pointers. Values have value semantics; parameters are borrowed by default, `mut p T` lets a function change the caller's variable in place."),
    ("E0133", "There are no comprehensions. Use methods with `it`: `xs.filter(it > 0).map(it * 2)`."),
    ("E0134", "There are no imports (the standard library is always in scope) and no top-level statements. Put code in `fn main() =`, which runs automatically."),
    ("E0135", "Bindings are not annotated. Write `x = value`; when the type matters for an empty collection, `var x [int] = []`."),
    ("E0136", "There are no impl blocks, traits or `self`. A method is a plain function whose first parameter is the receiver: `fn area(s Shape) f64 = ...` is called as `s.area()` or `area(s)`."),
    ("E0138", "There are no named arguments; pass arguments by position. Parameters may have defaults: `fn f(x int, step int = 1)`. For Python's keyword arguments: print without a newline with `io.write(s)`, sort descending with `xs.sort_by(-it)`, sort by a key with `xs.sort_by(it.age)`."),
    ("E0140", "Every parameter needs a type: `fn f(x int, name str)`."),
    ("E0141", "Enum variants carry positional fields: `enum Shape = Circle(f64) | Rect(f64, f64)`. Construct with `Circle(1.0)`."),
    ("E0142", "There is no C-style for. Use ranges: `for i in 0..n:`, `for i in (0..n).rev():`, `for i, x in xs.enumerate():`."),
    ("E0143", "Slices have no step. Use `xs.rev()` to reverse or `xs.step_by(n)` to take every nth element."),
    ("E0144", "There is no struct update syntax. Copy and set: `var v = u` then `v.age = 31` (copies are cheap; values are copied on write)."),
    ("E0145", "Optionals and results have no wrapper constructors. An optional is the value itself or `none`; a result is the value itself or an error. In `match`, use `none:` and `err(e):` arms, then a plain name for the value."),
    ("E0146", "Inside brackets, line breaks do not make blocks. A `match` there takes arms on their own lines, each one expression:\n  print(match op\n    \"+\": a + b\n    _: a - b)\nWhen an arm needs statements, bind the match first: `v = match op` with indented arms, then use `v`."),
    ("E0147", "There is no `if let` or `while let`. An optional is the value itself or `none`: `x = m.get(k)` then `if x != none:`, or `match` with a `none:` arm. Loop with `while !stack.is_empty():` and `x = stack.pop().unwrap()`."),
    ("E0148", "There is no `del`. Remove a map entry with `m.remove(k)` and a list item by index with `xs.remove(i)`; both need a `var`."),
    ("E0201", "The name is not defined at this point. Names bound inside a block (`if`, `for`, a match arm) end with the block: declare `var x = ...` before it, or bind the block's value: `x = if c: 1 else: 2`."),
    ("E0202", "The binding is immutable. Declare it with `var` to assign to it, change its fields or call `push`/`insert`/`remove` on it. A parameter can be changed when declared `mut p T`; the caller's variable is updated."),
    ("E0203", "No such field or method. Zero-argument methods may be written without parentheses (`xs.len`). Any function `fn f(x T, ...)` is also a method on `T`: `x.f(...)`."),
    ("E0204", "Unknown type. Built-in types: `int` (i64), `i8`..`i64`, `u8`..`u64`, `f64`, `f32`, `bool`, `str`, `[T]`, `{K:V}`, `{T}`, `(A, B)`, `T?`, `T!`."),
    ("E0205", "A name is defined twice, or a variant name is unknown or ambiguous. Qualify ambiguous variants: `Shape.Circle`. Pattern names that start with an uppercase letter must be variants."),
    ("E0206", "Wrong number of arguments or fields."),
    ("E0207", "A struct literal is missing fields. Give every field, positionally `User{\"ann\", 30}` or by name `User{name: \"ann\", age: 30}`, unless the field has a default."),
    ("E0208", "The struct has no field with this name."),
    ("E0209", "A `mut` parameter changes the caller's variable, so the argument must be a variable (or a field or element of one), not a temporary value."),
    ("E0210", "Only variables, fields (`u.age`) and elements (`xs[i]`, `m[k]`) can be assigned to."),
    ("E0211", "`break` and `continue` only work inside `for` and `while` loops."),
    ("E0212", "`as` converts between number types, `str` and `bool`: `n as f64`, `x as int`. The same conversions are available as calls: `f64(n)`, `int(x)`, `str(x)`."),
    ("E0213", "A `match` on an enum must cover every variant, or end with a `_:` arm."),
    ("E0215", "`lacon run` needs a `fn main()` (or `fn main()!`)."),
    ("E0301", "A value has the wrong type: a declared parameter, field or return type does not match, or an operator got operands it does not accept. Conditions must be `bool`; there is no truthiness. Ints become floats where a float is wanted; nothing else converts implicitly: use `str(x)`, `int(x)`, `f64(x)`."),
    ("E0302", "`?` and `fail` leave the function with a failure, so the function must say it can fail: `fn f(...) T!`. In a `T?` function, `x?` returns `none` when `x` is `none` or an error, and `fail` is not available (return `none`). `main` and tests can always use `?` and `fail`."),
    ("E0303", "Branches of different types (`f() ?? \"error\"`, `if c: 1 else: \"x\"`, `[name] + numbers`) make a value that can only be printed or interpolated. To use it otherwise, give every branch the same type, e.g. `match f()` with arms `err(_): \"error\"` and `v: str(v)`."),
    ("E0304", "A function with a return type must end with a value on every path. A trailing `if` needs an `else`; a loop that ends the body needs a `return` after it."),
    ("E0305", "A function without a return type returns nothing, so its call has no value to use. Declare the type: `fn double(x int) int = x * 2`. `main` returns nothing; set the exit code with `os.exit(code)`."),
    ("E0400", "`panic(msg)` was called."),
    ("E0402", "Index out of range. Negative indexes count from the end. `xs.get(i)` returns `none` instead of failing."),
    ("E0403", "Map key not found. `m.get(k)` returns `none` for a missing key and `m.get(k) ?? d` gives a default. `m[k] += 1` and `m[k].push(x)` create a missing entry first."),
    ("E0404", "Integer division or remainder by zero."),
    ("E0405", "Integer overflow, or a value that does not fit its declared integer type. Integers are 64-bit and overflow traps."),
    ("E0406", "A `T!` value may be an error, so it can't be used as a `T` or dropped. Add `?` to pass the error up (the function must return `T!`), use `x ?? default`, or `match x` with an `err(e):` arm."),
    ("E0407", "A `T?` value may be `none`, so it can't be used as a `T`. Check with `if x != none:` (after that, `x` is a `T`), give a default with `x ?? d`, or use `x?` in a function returning `T?` or `T!`."),
    ("E0408", "Recursion went too deep. Use a loop, or an explicit stack (`var stack = [start]` with `push`/`pop`)."),
    ("E0409", "Methods such as `sort`, `rev`, `trim`, `replace`, `map` and `filter` return a new value and leave the receiver unchanged. Assign the result: `xs = xs.sort()`."),
    ("E0410", "`push`, `pop`, `insert`, `remove`, `add`, `extend` and `clear` change their receiver, which must be a `var` (or a field or element of one). Strings are immutable; build new ones."),
    ("E0411", "No `match` arm matched the value. Add an arm or a final `_:` arm."),
    ("E0414", "The value does not have the shape the pattern expects (e.g. unpacking a 3-tuple into two names)."),
    ("E0420", "A test's final `a == b`, or an `assert a == b`, compared unequal values. Both sides and the first difference are shown."),
    ("E0421", "An `assert` condition was false."),
];

pub fn explain(code: &str) -> Option<&'static str> {
    let code = code.to_ascii_uppercase();
    ENTRIES.iter().find(|(c, _)| *c == code).map(|(_, t)| *t)
}
